### ISSUE TITLE
CSP error in donate site

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/donate-wagtail#1678]
Following completion of tickets #[1677](https://app.zenhub.com/workspace/o/mozilla/donate-wagtail/issues/1677) & #[1673](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/donate-wagtail/1673) the Digital Marketing team at TBX have tested the changes. 

An error is showing in the console for https://donate-wagtail.mofostaging.net/en-GB/

See attached ![Screenshot 2022-07-26 at 14.02.23.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/677a744f-59f9-4e3d-98cd-329680126024)

**Comment by danielfmiranda** [comment]
Hi Everyone! Just wanted to leave some findings from @mtdenton and I here for whoever works on this ticket.

It turns out, these 3 errors are not being generated by our code, but instead by a random inline script **(that has no effect on the functionality of payment processing)** that is being used by the braintree/paypal package. 

Since these files are used in the package themselves, there is no way for us to access these and pass in the nonce value.

According to documentation, if we[ upgrade braintree/paypal,](https://developer.paypal.com/braintree/docs/guides/paypal/paypal-sdk-migration-guide/javascript/v3)  we can then load in the paypal sdk manually like so:

```
<!-- Load the PayPal JS SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=your-sandbox-or-prod-client-id"></script>

<!-- Load the Braintree components -->
<script src="https://js.braintreegateway.com/web/3.85.3/js/client.min.js"></script>
<script src="https://js.braintreegateway.com/web/3.85.3/js/paypal-checkout.min.js"></script>
```

Which according to the [paypal documentation ](https://developer.paypal.com/reference/guidelines/browser-support/#link-contentsecuritypolicyrules), we can then pass in the nonce like so:

```
<script src="https://www.paypal.com/sdk/js?client-id=test" data-csp-nonce="xyz-123">
```

**Comment by cdanfon** [comment]
Hey @danielfmiranda this is great, thanks for adding the above explanation. 

As #1679 was a duplicate of this ticket, but assigned to you this sprint, would you please work on this ticket this sprint? Thanks!

**Comment by cdanfon** [comment]
The question/discussion is: do we want to invest time in fixing this?

**Comment by bheasman** [comment]
I think the issue here is less that it's breaking payments, but rather it's blocking GA which preventing us from setting up the donation funnel tracking in GA4. So I do think it'd be good to make a plan for this, unless there's a workaround that doesn't involve the Paypal/braintree upgrade (which seems a high effort approach, is that right @danielfmiranda ?)

**Comment by cdanfon** [comment]
completed via #1673
